config/routes.rb
Rails.application.routes.draw do

  root :to => 'page#home'
  get  '/courses',    to: 'courses#index'
  get  '/subjects',    to: 'subjects#index'
  get  '/instructors',    to: 'instructors#index'

  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  get  '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/enrolled', to: 'users#enrolled_course'
  post '/enroll/:course_id', to: 'users#enroll'
  post '/drop/:course_id', to: 'users#drop'

  post '/search', to: 'page#do_search'
  get '/search', to: 'page#show_search'

  resources :users
  resources :instructors
  resources :courses
  resources :subjects
  resources :enrollments

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :enrollments
    has_many :courses,:through => :enrollments
    before_save { email.downcase! }
    validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    validates :password_confirmation, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  include UsersHelper
  include SessionsHelper
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end


  def enrolled_course
    @user = current_user
    @courses = current_user.courses.all
    if @user
      render 'my_course'
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome #{@user.name}"
      redirect_to root_url
    else
      render 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def enroll
    if Enrollment.create(user_id: current_user.id, course_id: params[:course_id])
      flash[:success] = 'Successfully enrolled in this course'
    else
      flash[:danger] = 'The course has already been enrolled'
    end
    redirect_to enrolled_path
  end


  def drop
    e = Enrollment.where(user_id: current_user.id, course_id: params[:course_id]).first
    e.destroy
    flash[:success] = 'Successfully dropped the course'
    redirect_to enrolled_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end


end

app/helpers/users_helper.rb
module UsersHelper
require 'digest/md5'

    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email)
        gravatar_url = "https://www.gravatar.com/avatar/#{gravatar_id }"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    
    end

    


end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_showall.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
      </h1>
      <h3>Name: <%= @user.name %></h3>

      <h3>Email: <%= @user.email %></h3>
    </section>
  </aside>
</div><link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"><html>
<head>
  <title>Courses enrolled</title>

</head>


<h3 >Enrolled Courses:</h3>

<table class="table table-striped">
<thead>
<tr>
  <th>Code</th>
  <th>Name</th>
  <th>Description</th>
  <th colspan="3"></th>
</tr>
</thead>

<tbody>
<% @courses.each do |course| %>
  <tr>
    <td><%= course.id %></td>
    <td><%= course.name %></td>
    <td><%= course.description %></td>
    <td><%= link_to 'Drop', "/drop/#{course.id}", class: 'btn btn-primary', method: :post %></td>
  </tr>
<% end %>
</tbody>
</table>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/my_course.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
      </h1>
      <h3>Name: <%= @user.name %></h3>

      <h3>Email: <%= @user.email %></h3>
    </section>
  </aside>
</div><link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"><html>
<head>
  <title>Courses enrolled</title>

</head>


<h3 >Enrolled Courses:</h3>

<table class="table table-striped">
<thead>
<tr>
  <th>Code</th>
  <th>Name</th>
  <th>Description</th>
  <th colspan="3"></th>
</tr>
</thead>

<tbody>
<% @courses.each do |course| %>
  <tr>
    <td><%= course.id %></td>
    <td><%= course.name %></td>
    <td><%= course.description %></td>
    <td><%= link_to 'Drop', "/drop/#{course.id}", class: 'btn-lg btn-success', method: :post %></td>
  </tr>
<% end %>
</tbody>
</table>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h2  align="center">Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, url: signup_path, local: true) do |f| %>
      <%= render 'shared/error_message' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<br />
<div class="card">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
      </h1>
      <h3>Name: <%= @user.name %></h3>

      <h3>Email: <%= @user.email %></h3>
    </section>
  </aside>
</div>


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">