config/routes.rb
Rails.application.routes.draw do

  root :to => 'page#home'
  get  '/courses',    to: 'courses#index'
  get  '/subjects',    to: 'subjects#index'
  get  '/instructors',    to: 'instructors#index'

  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  get  '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/enrolled', to: 'users#enrolled_course'
  post '/enroll/:course_id', to: 'users#enroll'
  post '/drop/:course_id', to: 'users#drop'

  post '/search', to: 'page#do_search'
  get '/search', to: 'page#show_search'

  resources :users
  resources :instructors
  resources :courses
  resources :subjects
  resources :enrollments

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer mt-5 mb-3">
  <small>The <%= link_to 'Source code for Mini Latte @Ruby on rails', 'https://github.com/yuchenxuuu/PArails01-COSI166' %> by Yuchen</small>
</footer>

app/views/layouts/_navbar.html.erb
<link href="https://fonts.googleapis.com/css?family=Coda+Caption:800&display=swap" rel="stylesheet">
<nav class="nav navbar navbar-expand-lg navbar-fixed-top">
  <%= link_to "Mini Latte", root_path, class: "navbar-brand" %>
    <% if logged_in? %>
        <ul class="nav nav-tabs">
            <li>
                <%= link_to "Instructor Page", instructors_path %> 
            </li>
            <li>
                <%= link_to "Subject Page", subjects_path %> 
            </li>
            <li>
                <%= link_to "Course Page", courses_path %> 
            </li>
            <li><%= link_to "Search", search_path %></li>
         
            <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" role="button" data-toggle="dropdown">
                        Account
                </a>
                <ul class="dropdown-menu">
                        <li><%= link_to "Profile", current_user %></li>
                        <li><%= link_to "My Course", enrolled_path %></li>
                        <li class="divider"></li>
                        <li>
                        <%= link_to "Log out", logout_path, method: :delete %>
                        </li>
                </ul>
            </li>
        </ul>
    <% else %>
        <ul class="nav nav-tabs navbar-right">
            <li><%= link_to "Log in", login_path  %></li>
        </ul>
    <% end %>
</nav>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
   
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="body-container mx-auto">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>

        <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>